name: Build latest package
on: 
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v3

      # # will be needed later
      # - uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: v1.x # Run with latest stable Deno.

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: zlumer/ols:latest

      - name: Get package version number
        uses: martinbeentjes/npm-get-version-action@master
        id: package-version
      
      - name: Tag new version
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ steps.package-version.outputs.current-version}}
          git_tag_prefix: "v"
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
