name: Publish image to Docker Hub on tag
on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get package version number
        uses: martinbeentjes/npm-get-version-action@master
        id: package-version
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: zlumer/ols:${{ steps.package-version.outputs.current-version}}
